#! /bin/sh

sxhkd &
compton --backend glx -b -cz -t-4 -l-3 -r4 -o0.55 --blur-background --blur-method kawase --blur-strength 7 --vsync opengl --config /dev/null &
feh --bg-fill ~/Downloads/forest.jpg &
polybar -r -q kkustom &
polybar -r -q kkustom_bottom &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0 
bspc config window_gap           20

bspc config top_padding          25
bspc config bottom_padding       25
bspc config right_padding        25
bspc config left_padding         25

bspc config normal_border_color         "#25182A"
bspc config focused_border_color        "#4F4253"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Termite desktop='^1'
bspc rule -a discord desktop='^2'
bspc rule -a Google-chrome desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
